### PR TITLE
Initial commit for lambda

### PR DESCRIPTION
**Pull request by lcmorley**

### CODE REVIEW

**Comment by dllmorgan** [comment]
As a quick solution to avoiding the details in application.properites we can create a template file (also called application.properties) with no values assigned, i.e:

DATABASE_URL=
DATABASE_USER=
DATABASE_PASSWORD=
WRANGLER_NAME=LocalWrangler 

And then add it to the .gitignore file so your local version doesn't get pushed into github with the authentication details.

This does mean that anyone who copies the repo to their local machine to make further changes will need to add those details in, but that is probably okay as a short-term workaround.

**Comment by lcmorley** [comment]
> Looks good to me @lcmorley - Only one thing - The application.properties file shows the database username and password. I know PropertiesUtil accesses this and it stores them as AWS Environment variables but should we comment them out for pushing to GIT? Or is this only the test database you set up and therefore doesn't matter?

Good point, I have now removed it as it is not really relevant locally. I have also added an exception which is now thrown when a property is not found to enforce configuration when deployed. I have also added instructions to the README.md file to inform users of the expected configuration. Tests also updated.

**Comment by lcmorley** [comment]
> As a quick solution to avoiding the details in application.properites we can create a template file (also called application.properties) with no values assigned, i.e:
> 
> DATABASE_URL=
> DATABASE_USER=
> DATABASE_PASSWORD=
> WRANGLER_NAME=LocalWrangler
> 
> And then add it to the .gitignore file so your local version doesn't get pushed into github with the authentication details.
> 
> This does mean that anyone who copies the repo to their local machine to make further changes will need to add those details in, but that is probably okay as a short-term workaround.

Please see the response to @RyanAldy.

**Comment by sivagudur** [comment]
Look good to me Leon.  The good thing is you added unit tests to the lambda which utilizes Mockito and PowerMockito. The whole team should follow the same approach in testing.

**Pull request merged**
